-- Create meditations table
create table public.meditations (
  id bigint primary key generated by default as identity,
  title text not null,
  duration integer not null, -- in seconds
  file_name text not null,
  file_url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create feedback table (anonymous)
create table public.feedback (
  id bigint primary key generated by default as identity,
  meditation_id bigint references public.meditations(id) on delete cascade,
  wellbeing_change integer not null check (wellbeing_change between -2 and 2),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
alter table public.meditations enable row level security;
alter table public.feedback enable row level security;

-- Meditations policies
create policy "Meditations are viewable by everyone" 
on public.meditations
for select 
using (true);

-- Feedback policies - allow anonymous submissions
create policy "Anyone can submit feedback"
on public.feedback
for insert
using (true)
with check (true);

-- Create indexes for better query performance
create index meditations_created_at_idx on public.meditations(created_at desc);
create index feedback_meditation_id_idx on public.feedback(meditation_id);