-- Create meditations table
create table public.meditations (
  id bigint primary key generated by default as identity,
  title text not null,
  duration integer not null, -- in seconds
  file_name text not null,
  file_url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create feedback table with reference to Supabase auth.users
create table public.feedback (
  id bigint primary key generated by default as identity,
  user_id uuid references auth.users(id),
  meditation_id bigint references public.meditations(id) on delete cascade,
  wellbeing_change integer not null check (wellbeing_change between -2 and 2),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
alter table public.meditations enable row level security;
alter table public.feedback enable row level security;

-- Meditations policies
create policy "Meditations are viewable by everyone" 
on public.meditations
for select 
using (true);

-- Only authenticated users can insert feedback
create policy "Users can create feedback"
on public.feedback
for insert
to authenticated
with check (auth.uid() = user_id);

-- Users can only view their own feedback
create policy "Users can view own feedback"
on public.feedback
for select
to authenticated
using (auth.uid() = user_id);

-- Create indexes for better query performance
create index meditations_created_at_idx on public.meditations(created_at desc);
create index feedback_user_id_idx on public.feedback(user_id);
create index feedback_meditation_id_idx on public.feedback(meditation_id);